apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod
spec:
  labels:
    app: nginx
    demo: service
  containers:
  - name: ngnix-pod
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selectors:
    app: nginx
    demo: service
  ports:
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port