apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    demo: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      demo: deployment  
  template:  
    metadata:
      labels:
        app: nginx
        demo: deployment 
    spec: 
      containers:
      - name: hello-pod-deployment
        image: nginx:nginx/unit:1.29.1-minimal
          