apiVersion: v1
kind: Pod
metadata:
  name: ngnix-lb
  labels:
    app: nginx
    demo: loadbalancer
spec:
  containers:
  - name: ngnix-pod-2
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-servicenode
spec:
  type: LoadBalancer
  selector:
    app: nginx
    demo: loadbalancer
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port