apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod-1
  labels:
    app: nginx
    demo: servicenode
spec:
  containers:
  - name: ngnix-pod-1
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-servicenode
spec:
  type: NodePort
  selector:
    app: nginx
    demo: servicenode
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port