apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: hello-pod-2
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: devopssecret