apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    demo: rs
spec:
  replicas: 3
  selector:
    matchlabels:
      app: nginx
      demo: rs  
  template:  
    metadata:
      labels:
        app: nginx
        demo: rs 
    spec: 
      containers:
      - name: hello-pod-rs
        image: nginx
          