apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "80m"
        memory: "50Mi"
      limits:
        cpu: "100m"
        memory: "70Mi"